### ISSUE TITLE
Add developer scripts to `scripts` dir

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#173]
@rwdavis513 has a bunch of useful developer scripts he's created for openag_brain. They cover things like starting recipes, testing lights, etc.

We should add all these little scripts to the `scripts` dir so they are available via `rosrun openag_brain <script_name>`

**Comment by Spaghet** [comment]
Not sure what happened with this but @rwdavis513 is no longer actively part of the development team so I'm going to close this.
