### ISSUE TITLE
Add docker install script to openag_brain/scripts (0.5d)

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#184]
It would be useful to have a copy or git subtree of the script in https://github.com/openaginitiative/openag_brain_docker_rpi.

(Exported from Trello https://trello.com/c/KXFBLQHk/994-add-docker-install-script-to-openag-brain-scripts-0-5d)

**Comment by rwdavis513** [comment]
Is this done already?

**Comment by gordonbrander** [comment]
Nope! https://github.com/OpenAgInitiative/openag_brain_docker_rpi/blob/master/install_docker.sh
