### ISSUE TITLE
Create Docker image for openag cloud (CouchDB, etc)

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#192]
https://github.com/OpenAgInitiative/openag_repo

(Exported from Trello https://trello.com/c/HAw3L2Lr/513-create-docker-image-for-openag-cloud-couchdb-etc)

**Comment by rwdavis513** [comment]
This probably isn't needed since we have a separate repository containing the openag_cloud code. The new one is already containerized.

**Comment by Spaghet** [comment]
It's not OSS :'(
