### ISSUE TITLE
Create new Recipe_handler to process new time format. Start/stop recipes (3d)

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#194]
https://github.com/OpenAgInitiative/openag_brain/issues/79

- Pause means &quot;break all feedback loops&quot;.
  - Depends on https://trello.com/c/H0WGwXJA/912-way-to-break-feedback-loops-when-recipe-is-finished-paused-null-setpoints-2d

(Exported from Trello https://trello.com/c/EPANisO4/564-create-new-recipe-handler-to-process-new-time-format-start-stop-recipes-3d)

---

On 2017-04-27T17:55:52.387Z, @bobdavis27 wrote:

 (add pause, seek, start @ given time) 

---

On 2017-03-30T20:37:46.085Z, @gordonbrander wrote:

This is required for https://trello.com/c/b5i4IQdy/516-update-ui-control-panel-to-retain-state-override-recipe.

**Comment by rwdavis513** [comment]
This was resolved with PR#266.
