### ISSUE TITLE
Figure out why ui camera feed has bad image

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#204]
https://github.com/jakerye/pfc2-issues/blob/master/2017_04_20_camera_feed_has_bad_image.md

(Exported from Trello https://trello.com/c/mme79PA6/993-figure-out-why-ui-camera-feed-has-bad-image)

**Comment by Spaghet** [comment]
This is an interesting one...we'll see if it happens on fswebcam

**Comment by gordonbrander** [comment]
I think this is because the file sometimes gets accessed at the same time it is being written.
