### ISSUE TITLE
Graceful error logging when Arduino goes down

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#211]
Currently if the Arduino goes down, it seems to take down the whole docker container? Find out why and how to handle this case gracefully, logging issue to logs.

(Exported from Trello https://trello.com/c/POIKyidH/928-graceful-error-logging-when-arduino-goes-down)

---

On 2017-04-18T23:07:16.421Z, @bobdavis27 wrote:

It would also be helpful to include some kind of notification for when this happens so that the appropriate action can be taken. Perhaps a full health check node would be valuable for monitoring in case anything stops working.

**Comment by Spaghet** [comment]
We pretty much fixed this with bespoke serial. We don't have a docker image of this yet but I assume it's on the list for master merge
