### ISSUE TITLE
Recipe page with URL for every recipe in cloud DB

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#220]
(Exported from Trello https://trello.com/c/Qp3NVnLP/536-recipe-page-with-url-for-every-recipe-in-cloud-db)

**Comment by rwdavis513** [comment]
Would this be an API end point to display the recipe in a friendly format? Or something else?

**Comment by Spaghet** [comment]
I'm going to close this since this is a cloud issue
