### ISSUE TITLE
Tune ph loop / modify ph doser firmware

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#227]
when going from ph 5 to 6, ph overshot to 7.5 and dosed 1/5 of the bottle.
also it seems like the more up/down soln that are in the basin, the harder it is to raise / lower

(Exported from Trello https://trello.com/c/QjeXaIKw/991-tune-ph-loop-modify-ph-doser-firmware)

**Comment by Spaghet** [comment]
Fixed in #314
