### ISSUE TITLE
[rospack] Error: package 'openag_brain' not found

### ISSUE THREAD

**Issue by jaredsalazar** [OpenAgInitiative/openag_brain#24]
i used the instruction from openag_brain_rpi and run the `rosrun openag_brain main` but he message i got is `[rospack] Error: package 'openag_brain' not found`. In the instruction is says 

> with catkin workspace active

how will i know if its active or not?

**Comment by LeonChambers** [comment]
You have to activate the workspace by sourcing the file `devel/setup.bash` in the catkin workspace in which the openag_brain code was installed

**Comment by jaredsalazar** [comment]
ok, got it. It runs now.
