### ISSUE TITLE
Remove topic_connector.py

### ISSUE THREAD

**Issue by rwdavis513** [OpenAgInitiative/openag_brain#241]
Allow the commanded topics to publish directly to the controllers and receive messages directly from the sensors

**Comment by gordonbrander** [comment]
* This disentangles Arduino from ROS code, making it easier to move off of Arduino.
    * Example https://github.com/gordonbrander/openag_brain/blob/python_peripherals/nodes/sensor_am2315.py
    * API
      * Publish to the set of supported environmental variable.
        * type: (AIR_TEMPERATURE, WATER_TEMPERATURE...)
        * value: per type

**Comment by Spaghet** [comment]
Topic connector no longer runs as of #271, closing.
