### ISSUE TITLE
[Exploration] Replace rosserial with bespoke serial protocol

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#247]
## Summary

Replace rosserial with a simple custom serial protocol (probably CSV) and a corresponding Python ROS node that knows how to interpret the protocol and publish the result to ROS topics.

## Motivation

rosserial has a number of issues:

- Opaque error messages. Multiple error cases result in same message. https://github.com/OpenAgInitiative/openag_brain/issues/167
- A limited number of topics is supported (and we are already up against the limit) https://github.com/OpenAgInitiative/openag_brain/issues/238
- The topic buffer is constrained and it is easy to spill over. The actual bandwidth for serial is waaaay more than rosserial allows.

As well as other issues https://github.com/OpenAgInitiative/openag_brain/issues/237https://github.com/OpenAgInitiative/openag_brain/issues/237

Most high-impact issues in the system are currently caused by rosserial. See https://github.com/OpenAgInitiative/openag_brain/issues?q=is%3Aopen+is%3Aissue+label%3Arosserial for tracking these issues.

**Doing this would fix https://github.com/OpenAgInitiative/openag_brain/issues/239, https://github.com/OpenAgInitiative/openag_brain/issues/238, https://github.com/OpenAgInitiative/openag_brain/issues/237, https://github.com/OpenAgInitiative/openag_brain/issues/167 and possibly https://github.com/OpenAgInitiative/openag_brain/issues/166.**

## Details

- Define a simple protocol that allows us to send info over serial to a ROS node
  - CSV or JSON
- Message (stringified)
  - int (control char representing pin or address or var type
  - float (value)
- Use newline char as EOM terminator (makes it work with serial monitor)

Design goals:

- Make the Arduino as dumb as possible. Just read and write to pins.
- Config in params in Python/ROS land.
- DO NOT try to create a generalized protocol (like Firmada). The goal is the simplest thing that can possibly work robustly. The ROS node should be tightly coupled to the firmware sketch.

Questions:

- Send readings separately or together?
- Retain last state and send that?

Things to consider:

- Handle error cases
- Don't overflow Arduino serial buffer
  - Rate limiting?
- Baud rate
- Loop frequency
- Buffer strategy (don't overwhelm it)

## Drawbacks

...

## Alternatives

- Remove the Arduino altogether and use the GPIO pins on the SBC
  - This would require a wire harness or new signal board that fits the Pi's form factor

**Comment by gordonbrander** [comment]
Related #202, #246

**Comment by wsnook** [comment]
In case it might give you some ideas, here's an example trace of the serial port protocol I'm using:
```
> help
 Commands:
  ds18b20  Get tank C with DS18B20
     tank  Get all tank sensor values
   si7021  Get air C & %RH with Si7021
   bme280  Get air C, %RH & hPa with BME280
      air  Get all air sensor values
   red on  Red LED on
  red off  Red LED off (default)
   yel on  Yellow LED on
  yel off  Yellow LED off (default)
     wifi  Get wifi status
  wifi on  Enable wifi for flashing firmware
 wifi off  Airplane mode (default)
     help  Show this help message

 To disconnect from screen, use ctrl-a k.
 For cu, use ~~. inside an ssh session, or
 use ~. locally.
> ds18b20
tank:C=26.1:sensor=DS18B20
> air
air:C=26.2:%RH=53.0:sensor=Si7021
air:C=26.6:%RH=51.1:hPa=964.7:sensor=BME280
> tank
tank:C=26.1:sensor=DS18B20
> si7021
air:C=26.2:%RH=52.9:sensor=Si7021
> bme280
air:C=26.6:%RH=51.3:hPa=964.7:sensor=BME280
> red on
> red off
> wifi
wifi:airplaneMode=true:RSSI=0
```

**Comment by gordonbrander** [comment]
@Spaghet did a quick prototype of this approach for sensors using a simple CSV string message format that sends an status code along with an ordered list of messages from each sensor.

- The Arduino sketch sends CSV along with status code for debugging
- The ROS node is tightly coupled with the Arduino sketch.
  - It manages the Arduino and most of the smarts should exist at this layer.
  - It knows the CSV column order and how to parse the bespoke message format.
  - It's job is to parse out the message and publish status as well as values to ROS topics

CSV format is nice because it can also be hooked up to the Arduino serial monitor for testing.

**Comment by wsnook** [comment]
@gordonbrander Looks cool.

**Comment by CarrierDirectJoe** [comment]
I've been adding source ino files to my firmware libs exactly because I can't see into the std:msg payloads that come from the raspberry pi. It would be great to have a proper output to verify against before incorporating into a lib / ROS.

**Comment by gordonbrander** [comment]
@CarrierDirectJoe proper output meaning strings printed to serial monitor?

**Comment by novemberalpha** [comment]
Ya, sorry. It was hard to debug gc0011 because I couldn't read the ROS outputs to serial and didn't really have a debug harness or whatnot. So serial output was what I hacked around.

**Comment by novemberalpha** [comment]
Also sorry for changing accounts. I try to respond on my personal account and not work. :-)

**Comment by gordonbrander** [comment]
Prototype ROS node. It still needs to be able to handle short reads. https://github.com/Spaghet/test_serial/blob/master/nodes/arduino_handler.py

**Comment by Spaghet** [comment]
#271
