### ISSUE TITLE
simple and flex recipe handlers use different time objects

### ISSUE THREAD

**Issue by rbaynes** [OpenAgInitiative/openag_brain#269]
The RecipeHandler class, get_state() function returns time values as float seconds from a rospy.get_time() call.   That is what the interpret_simple_recipe() expects/uses.

The interpret_flexformat_recipe() expects datetime objects.

Decide on the one time to rule them all and fix the code.

Blocking the master branch from running flex recipes.

**Comment by rwdavis513** [comment]
Fixed with PR [#273](https://github.com/OpenAgInitiative/openag_brain/pull/273)

**Comment by rwdavis513** [comment]
PR merged into the develop branch. Closing out this issue.
