### ISSUE TITLE
openag_module.h: no such file or directory

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#30]
After running openag brain docker image, configuring and hooking up a sensor, I get the following error during code gen:

    [WARN] Cloning into 'openag_ds18b20'
    [WARN] In file included from /tmp/tmphL7oHh/src/src.ino:2:0:
    [WARN] .pioenvs/megaatmega2560/openag/ds18b20/openag_ds18b20.h:16:27: fatal error: openag_module.h: No such file or directory
    [WARN] #include <openag_module.h>
    [WARN] ^
    [WARN] compilation terminated

**Comment by LeonChambers** [comment]
This is a problem with the default fixture. You just have to update the entry for ds18b20 to match the module.json file in the openag_ds18b20 repo
