### ISSUE TITLE
Bug in get_topic_info endpoint

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#46]
Variable `master` does not exist in scope. We want `rostopic_master`. See https://github.com/OpenAgInitiative/openag_brain/blob/master/src/openag_brain/software_modules/api.py#L175

**Comment by LeonChambers** [comment]
Can you submit a PR for this?

**Comment by gordonbrander** [comment]
Yup it's on the way.

**Comment by gordonbrander** [comment]
@LeonChambers here you go: https://github.com/OpenAgInitiative/openag_brain/pull/47
