### ISSUE TITLE
measured and desired topics are not prefixed by environment

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#72]
Is this intentional?

<img width="318" alt="screen shot 2016-10-21 at 4 29 03 pm" src="https://cloud.githubusercontent.com/assets/58421/19614609/bdb18990-97ab-11e6-88d2-674f1941d8dc.png">

(I've configured binary_actuator with `"input": {"variable": "light_illuminance"}` and a software module with `"parameters": {"variable": "light_illuminance"}`)

Won't this cause collisions if we have more than one environment?

cc @LeonChambers

**Comment by gordonbrander** [comment]
Update: never mind. No collision, because the topic is `/actuators/<id>/cmd`.

**Comment by LeonChambers** [comment]
My guess is that you didn't specify an environment for the controller. We should add a check to the controller code that prevents this from happening. For reference, I did a check like this for the video_writer module [here](https://github.com/OpenAgInitiative/openag_brain/blob/master/src/openag_brain/software_modules/video_writer.py#L153)
