### ISSUE TITLE
Remove dependency on ROS for building docs

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#78]
The one annoying thing getting the version number from the XML file without pulling in all of ROS (we currently use a ROS function that takes care of this magically).

**Comment by serein7** [comment]
Download single file from other repo and parse it out? http://stackoverflow.com/questions/4604663/download-single-files-from-github

**Comment by gordonbrander** [comment]
I think we can keep the file in this repo and use the `xml` package to grab the version number.

**Comment by LeonChambers** [comment]
Well, if we let the [ROS buildfarm](http://wiki.ros.org/build.ros.org) compile our docs, then this isn't really a problem, and ROS is willing to host documentation for open source projects for free. However, we might want all of our documentation hosted in the same place, and not all of our code is in ROS packages.

That being said, parsing the XML file ourselves really isn't that hard, but we should figure out where to host the docs anyway.

**Comment by rallytime** [comment]
I think this issue can be closed now? :)
