### ISSUE TITLE
recipe_handler.py continues to publish setpoints after recipe ends

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#92]
What happens:

- After recipe ends, the last setpoint is continually published to desired ROS topics

What should happen:

- After recipe ends, no further desired messages should be sent by `recipe_handler.py`.

**Comment by LeonChambers** [comment]
This is actually on purpose. There's no sense of when a recipe actually "ends", so after the last set point, it's not clear when to stop publishing desired variable values, so I just had it keep publishing indefinitely. A better solution would be to update the recipe structure to have a way of indicating when the recipe is actually over.
